server:
  port: 9090

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  instance:
    hostname: admin-server
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
