zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**
  ribbon:
    eager-load:
      enabled: true
      clients: customers-service, vets-service, visits-service, admin-server, discovery-server, hystrix-dashboard, tracing-server, api-gateway
  #SendErrorFilter:
    #post:
      #disable: true
  # stripPrefix: false

#---
#hystrix:
 # command:
  #  default:
   #   execution:
    #    timeout:
     #     enabled: false
---
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
---
ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 3000
  ReadTimeout: 60000
  
---
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411

---
eureka:
  #instance:
    #hostname: api-gateway
  client:
    fetchRegistry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
 



