server:
  port: 9411

#---
#spring:
 # profiles: default
#eureka:
 # instance:
    # enable to register multiple app instances with a random server port
  #  instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  application:
    name: tracing-server
  config:
    activate:
      on-profile: docker

---
eureka:
  instance:
    hostname: tracing-server
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    fetchRegistry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
